name = "raul"
account_id = "1b5b99f85df2ff3830dfec7cb7cee2d9"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = { bucket = "./build", entry-point = "workers-site" }
compatibility_date = "2022-03-17"

[build]
command = ""

[build.upload]
format = "service-worker"
